name: Tests

on:
  workflow_call:

  workflow_dispatch:

jobs:
  tests:
    name: Run Tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install .

      - name: Run tests
        run: pytest -s -vvvv -l --tb=long test

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: pip install black
      
      - name: Lint Code Base
        run: |
          black --check .